spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# File upload
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.ignore-migration-patterns=*:missing

# Server
server.port=${SERVER_PORT:8080}

# Cloudinary
cloudinary.url=${CLOUDINARY_URL}
# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=604800000
